spring:
  profiles:
    active: dev
  rabbitmq:
    host: 47.96.173.142
    port: 5672
    username: guest
    password: guest
  redis:
    host: 47.96.173.142
    password: paascloud@redis
    port: 6379
    timeout: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: paascloud
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 10
    min-idle: 10
    max-active: 20
    test-on-borrow: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@paascloud-eureka:8761/eureka/
paascloud:
  server:
    eureka:
      port: 8761
      hostname: paascloud-eureka
      serviceUrl: http://root:root@paascloud-eureka:8761/eureka/
    discovery:
      port: 8080
      hostname: paascloud-discovery
      serviceUrl: http://admin:admin@paascloud-discovery:8080
    gateway:
      port: 80
      hostname: paascloud-gateway
    monitor:
      port: 8010
      hostname: paascloud-monitor
      serviceUrl: http://paascloud-monitor:8010
    zipkin:
      port: 8020
      hostname: paascloud-zipkin
      serviceUrl: http://paascloud-zipkin:8020
    provider:
      ehc:
        port: 8040
        hostname: paascloud-provider-ehc
      mdc:
        port: 8030
        hostname: paascloud-provider-mdc
      omc:
        port: 8050
        hostname: paascloud-provider-omc
      opc:
        port: 8070
        hostname: paascloud-provider-opc
      ptc:
        port: 8060
        hostname: paascloud-provider-ptc
      uac:
        port: 8000
        hostname: paascloud-provider-uac
    web:
      mall:
        port: 9000
        hostname: paascloud-web-mall
  auth:
    jwt:
      expiredRemainMinutes: 20
      expiredMinutes: 120
  mail:
    host: smtp.sina.com
    username: 'your email address'
    password: 'your email password'
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          timeout: 2500
          starttls:
            enable: true
            required: true
  aliyun:
    key:
      accessKeyId: 'your aliyun accessKeyId'
      accessKeySecret: 'your aliyun accessKeySecret'
    rocketMq:
      namesrvAddr: 47.96.173.142:9876
    sms:
      signName: 快乐学习网
      regionId: cn-beijing
      endpoint:
      endpointName: cn-beijing
      product: 'your sms product'
      domain: dysmsapi.aliyuncs.com
  qiniu:
    key:
      accessKey: 'your qiniu accessKey'
      secretKey: 'your qiniu secretKey'
    oss:
      privateHost: 'your qiniu oss private host'
      publicHost: 'your qiniu oss public host'
  alipay:
    callback:
      url: http://dev-api.paascloud.net/omc/pay/alipayCallback
    qrCode:
      pcPath: E:/File/alipay/QRCode
      qiniuPath: alipay/QRCode/